{
 "title": "Dashboard-Classification_of_requests_based_on_time",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": " percentage of packets at processing 0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '0') / count(treatment_progress) From Packet_Informations\r\n",
     "rawQueryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '0') / count(treatment_progress) From Packet_Informations\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": " percentage of packets at processing 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '1') / count(treatment_progress) From Packet_Informations\r\n",
     "rawQueryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '1') / count(treatment_progress) From Packet_Informations\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": " percentage of packets at processing 2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '2') / count(treatment_progress) From Packet_Informations\r\n",
     "rawQueryText": "SELECT 100 * (SELECT COUNT(treatment_progress) FROM Packet_Informations WHERE treatment_progress = '2') / count(treatment_progress) From Packet_Informations\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Classification of requests based on time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT CAST(strftime(timestamp_capture_packet) as INTEGER) as time, count(*) as Normal from Packet_Informations INNER JOIN Image_Classification on Packet_Informations.packet_informations_id = Image_Classification.packet_informations_id INNER JOIN Packet_Data on Packet_Data.packet_data_id = Packet_informations.packet_data_id where classification = 'Normal' group by time order by time",
     "rawQueryText": "SELECT CAST(strftime(timestamp_capture_packet) as INTEGER) as time, count(*) as Normal from Packet_Informations INNER JOIN Image_Classification on Packet_Informations.packet_informations_id = Image_Classification.packet_informations_id INNER JOIN Packet_Data on Packet_Data.packet_data_id = Packet_informations.packet_data_id where classification = 'Normal' group by time order by time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT CAST(strftime(timestamp_capture_packet) as INTEGER) as time, count(*) as Abnormal from Packet_Informations INNER JOIN Image_Classification on Packet_Informations.packet_informations_id = Image_Classification.packet_informations_id INNER JOIN Packet_Data on Packet_Data.packet_data_id = Packet_informations.packet_data_id where classification = 'Abnormal' group by time order by time",
     "rawQueryText": "SELECT CAST(strftime(timestamp_capture_packet) as INTEGER) as time, count(*) as Abnormal from Packet_Informations INNER JOIN Image_Classification on Packet_Informations.packet_informations_id = Image_Classification.packet_informations_id INNER JOIN Packet_Data on Packet_Data.packet_data_id = Packet_informations.packet_data_id where classification = 'Abnormal' group by time order by time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}